/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wsl.works.crypto.io.cex;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
